AMQP_URI: amqp://${RABBIT_USER}:${RABBIT_PASSWORD}@${RABBIT_HOST}:${RABBIT_PORT}/
# LOGGING:
#     version: 1
#     handlers:
#         console:
#             class: logging.StreamHandler
#     root:
#         level: DEBUG
#         handlers: [console]
